version: '3.8'

services:
  db-escola:
    image: mysql:8.0
    container_name: db-escola
    environment:
      MYSQL_ROOT_PASSWORD: root-db-escola
      MYSQL_DATABASE: db-escola
      ports:
        - "3306:3306"
        volumes:
          - mysql_data:var/lib/mysql

volumes:
  mysql_data: